"""This file holds segment tree support classes
"""
class SegmentTreeNode(object):
    """Simple class to hold the necessary information for a node of the segment
    tree"""
    def __init__(self, func_name):
        """Initialize the segment tree node with the name for the segment

        Parameters
        ----------
        func_name : str
            Name of the function in the root file
        """
        # each composition is a full set of nodes that add together to make
        # this particular segment. If this is a leaf node the compositions list
        # is left empty
        self.comps = []
        self.function_name = func_name

    def add_composition(self, func_list):
        """Add a composition to a segment, a composition is a list of child
        SegmentTreeNodes

        Parameters
        ----------
        func_list : list
            list of SegmentTreeNodes
        """
        self.comps.append(func_list)

    def get_fun_name(self):
        """Return the segments function name

        Returns
        -------
        function_name : str
            The name of the function in the root file
        """
        return self.function_name

    def is_leaf(self):
        """Return if the segment is a leaf or not, i.e. does it have no child
        segments. If not it is at the bottom of the tree and is a child

        Returns
        -------
        function_name : str
            The name of the function in the root file
        """
        return len(self.comps) == 0

    def print_self_and_children(self, line_str, base_str):
        """Prints this node and its children in a visually reasonable manner
        via recursion"""
        # construct the output string
        print (line_str + self.function_name)
        for i, comp in enumerate(self.comps):
            print (base_str + "|-Composition# {0:d}".format(i))
            for seg in comp:
                seg.print_self_and_children(base_str + "|--",
                                            base_str + "|  ")
            


class SegmentInfo(object):
    """Class to hold information about the segment for the segment dictionary
    """
    def __init__(self, is_simple, is_built, node_ref):
        """Initializes the segment information

        Parameters
        ----------
        is_simple : boolean
            Is this one of the leafs or sums of quartets or a custom sum
        is_built : boolean
            Is this function already existent within the root file
        node_ref : SegmentTreeNode
            The node representing this segment
        """
        self.is_simple = is_simple
        self.is_built = is_built
        self.node_ref = node_ref

    def get_node(self):
        """Gets the node reference of the object

        Returns
        -------
        node_ref : SegmentTreeNode
            The segment tree node that represents the function
        """
        return self.node_ref

    def get_build_status(self):
        """Gets if the segment has been summed yet

        Returns
        -------
        build_status : bool
            True if the segment exists in the root file, false otherwise
        """
        return self.is_built

    def get_is_simple(self):
        """Gets if the segment is a simple piece generated by quartet summing
        or if it is one of the more complex sums in non even shapes

        Returns
        -------
        is_simple : bool
            True if the segment is one of the basic quartet summed or base
            segments, false otherwise
        """
        return self.is_simple


def gen_quartet_names(fmt_str, curr_segs, inds):
    """This function generates the 1 level of divisions down from what is
    passed to it

    Parameters
    ----------
    fmt_str : str
        The name generating format string
    curr_segs : int
        The segmentation at the current level
    inds : tuple
        A tuple of two integers holding the two current segment indices

    Returns
    -------
    seg_name_list : list of strings
        list of names of the 4 segments comprising the one passed to this func
    """
    seg_name_list = []
    off1 = 2*inds[0]
    off2 = 2*inds[1]
    for i in range(2):
        for j in range(2):
            seg_name_list.append(fmt_str.format(curr_segs*2,
                                                off1 + i, off2 + j))
    return seg_name_list
